# Generated by Django 5.2 on 2025-04-30 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EID", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("date_of_joining", models.DateField()),
                (
                    "business_unit",
                    models.CharField(
                        choices=[
                            ("Consumer Division", "Consumer Division"),
                            ("Prime Pusti Limited", "Prime Pusti Limited"),
                            ("Prime Cosmetics Limited", "Prime Cosmetics Limited"),
                            ("T.K. Logistics", "T.K. Logistics"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("Prime Pusti Limited", "Prime Pusti Limited"),
                            ("Prime Cosmetics Limited", "Prime Cosmetics Limited"),
                            (
                                "Super Oil Refinery Limited",
                                "Super Oil Refinery Limited",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_month", models.DateField()),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ma", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ea", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payable_days", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_payable_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "provident_fund",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "benevolent_fund",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "food_consumption",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("loan", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "exceed_mobile_bill",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "other_deduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("arrear", models.DecimalField(decimal_places=2, max_digits=10)),
                ("car_allowance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalaryInfo.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("reference_number", models.CharField(max_length=50)),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalaryInfo.salary",
                    ),
                ),
            ],
        ),
    ]
