# Generated by Django 5.2 on 2025-05-04 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SalaryInfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="cash_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="PaySlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("salary", models.ManyToManyField(to="SalaryInfo.salary")),
            ],
        ),
    ]
