# Generated by Django 5.2 on 2025-05-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SalaryInfo", "0002_employee_cash_salary_payslip"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelFileProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
